src/main/java/com/gogym/config/AppConfig.java

Test : 배포 테스트용 입니다.

---

src/test/java/com/gogym/member/controller/AuthControllerTest.java

Test : 배포 오류 해결을 위한 주석처리

---

src/test/java/com/gogym/GoGymApplicationTests.java
src/test/resources/application-test.yml

Test : 배포 테스트 오류 해결

---

src/main/java/com/gogym/config/JwtTokenProvider.java
src/test/resources/application-test.yml

TEST : 배포 오류 해결

---

src/main/java/com/gogym/member/service/MemberService.java

Comment : 구현중인 기능 주석처리

---

src/test/java/com/gogym/member/service/AuthServiceTest.java

Test : 테스트 코드 수정

---

src/main/java/com/gogym/aop/LoginMemberIdHandler.java
src/main/java/com/gogym/common/annotation/LoginMemberId.java
src/main/java/com/gogym/config/SecurityConfig.java
src/main/java/com/gogym/member/controller/AuthController.java
src/main/java/com/gogym/member/dto/LoginResponse.java
src/main/java/com/gogym/member/dto/ResetPasswordRequest.java
src/main/java/com/gogym/member/dto/SignInRequest.java
src/main/java/com/gogym/member/dto/SignUpRequest.java
src/main/java/com/gogym/member/entity/Member.java
src/main/java/com/gogym/member/entity/Role.java
src/main/java/com/gogym/member/jwt/JwtAuthenticationFilter.java
src/main/java/com/gogym/member/jwt/JwtTokenProvider.java
src/main/java/com/gogym/member/repository/MemberRepository.java
src/main/java/com/gogym/member/service/AuthService.java
src/main/java/com/gogym/member/service/EmailService.java
src/main/java/com/gogym/member/service/MemberService.java
src/main/java/com/gogym/util/RedisUtil.java
src/test/java/com/gogym/member/service/AuthServiceTest.java

멤버(회원) 관련 기능 #2
회원 인증 기능 시큐리티 설정 및 서버 연동 간 확인된 버그들 수정했습니다.
로컬환경에서 테스트 확인되었습니다.

✨ feat : 회원 인증 기능

---

src/main/java/com/gogym/gympay/repository/PaymentRepository.java

🚑️ hotfix: id 타입 수정

---

src/main/java/com/gogym/post/repository/PostRepository.java
src/main/java/com/gogym/post/service/PostService.java

- 잘못된 import 문 수정
- 게시글 상태를 받아오는 메서드 구현

✨feat : 게시글 상태를 반환하는 메서드 작성, 잘못된 import refactor

---

src/main/java/com/gogym/gympay/service/SafePaymentService.java

♻️refactor: ChatRoomService -> ChatRoomQueryService 사용

---

src/main/java/com/gogym/exception/ErrorCode.java
src/main/java/com/gogym/gympay/controller/TransactionController.java
src/main/java/com/gogym/gympay/dto/request/UpdateDateRequest.java
src/main/java/com/gogym/gympay/entity/constant/TransactionStatus.java
src/main/java/com/gogym/gympay/service/SafePaymentService.java
src/main/java/com/gogym/gympay/service/TransactionService.java

거래 일정 등록 api를 구현했습니다. 
채팅방 내에서 게시글 상태를 변경할 때 거래가 생성되거나 Status가 변경될 수 있도록 했습니다.

✨ Feat: 거래 일정 등록 및 거래 상태 변경에 따른 메서드 추가

---

src/main/java/com/gogym/member/controller/AuthController.java
src/main/java/com/gogym/member/service/AuthService.java

♻️refactor : 회원가입 - 로그인 카카오 연동 일시 비활성화

---

src/main/java/com/gogym/config/SecurityConfig.java
src/main/java/com/gogym/config/WebConfig.java

♻️refactor : cors 설정 변경

---

src/main/java/com/gogym/member/dto/MemberProfileResponse.java
src/main/java/com/gogym/member/entity/Member.java
src/main/java/com/gogym/member/service/MemberService.java

마이 페이지에서 Gympayid 가져오는 부분 누락한 것 추가했습니다.
회원 탈퇴 (소프트) 진행 시 마스킹 처리가 원본<->벤 테이블 간 로직이 거꾸로 작성된 부분 수정했습니다.

♻️refactor: 마이페이지에 gympayid 추가

---

src/main/java/com/gogym/gympay/entity/GymPay.java
src/main/java/com/gogym/gympay/service/TransactionService.java

🐞fix: 충돌 해결 중 잘못된 코드 수정

---

src/main/java/com/gogym/gympay/repository/impl/TransactionRepositoryImpl.java
src/main/java/com/gogym/notification/service/NotificationService.java
src/main/java/com/gogym/post/dto/PostPageResponseDto.java
src/main/java/com/gogym/post/repository/PostRepository.java
src/main/java/com/gogym/post/service/PostService.java
src/test/java/com/gogym/post/service/PostServiceTest.java

#106
📌 작업 이유 (Why)
- 구독 연결이 안되는 시점을 정확히 파악하기 위한 디버깅용 로그 추가
✨ 변경 사항 (Changes)
- FE 와 연동 테스트 도중 디테일 하게 구독이 되지 않는 상황을 파악하기 위해 로그 추가

♻️refactor : sse 구독 서비스 로그 변경, 게시글 반환 값 post type 추가

---

src/main/java/com/gogym/config/SecurityConfig.java
src/main/java/com/gogym/member/controller/AuthController.java
src/main/java/com/gogym/member/dto/MemberProfileResponse.java
src/main/java/com/gogym/member/jwt/JwtTokenProvider.java
src/main/java/com/gogym/member/service/AuthService.java
src/main/java/com/gogym/member/service/MemberService.java
src/test/java/com/gogym/member/service/AuthServiceTest.java

1. 회원 탈퇴 관련
2. 카카오 멤버 회원가입 관련
3.

♻️ refactor : 회원 처리 관련 전체 리팩토링 

---

src/main/java/com/gogym/member/entity/Member.java
src/main/java/com/gogym/post/entity/Post.java
src/main/java/com/gogym/post/service/PostService.java

♻️refactor : 게시글, 멤버 엔티티 수정

---

src/test/java/com/gogym/chat/service/impl/ChatMessageBatchSchedulerTest.java

✅ test: 변경된 로직으로 인한 테스트 코드 수정

---

src/main/java/com/gogym/member/dto/MemberProfileResponse.java
src/main/java/com/gogym/member/service/MemberService.java

1. 통합 테스트 중 민혁님이 요청하신 마이페이지에 지역 반환 추가 값 추가했습니다.

♻️ refactor: 마이페이지에 지역 반환 추가

---

src/main/java/com/gogym/member/entity/Member.java
src/main/java/com/gogym/member/service/MemberService.java
src/main/java/com/gogym/region/service/RegionService.java
src/main/resources/data.sql
src/test/java/com/gogym/member/service/MemberServiceTest.java

1. 지역 관련 오류 해결 리팩토링했습니다
2. 관련 테스트 코드 수정했습니다.
3. 프로필 관련 메서드도 수정했습니다 (부모-자식 관계가 없는 도시(세종시)를 참조할때 나는 오류 해결)

♻️ refactor: 지역 관련 오류 해결 리팩토링

---

src/main/java/com/gogym/member/service/MemberService.java

♻️refactor : 멤버 프로필 로직 수정

---

src/main/java/com/gogym/member/controller/KakaoController.java
src/main/java/com/gogym/member/service/KakaoService.java

♻️ refactor : 카카오 로직 변경

---

src/main/java/com/gogym/config/SecurityConfig.java
src/main/java/com/gogym/member/controller/KakaoController.java

♻️ refactor: 카카오 로직 테스트 수정 사항 반영

---

src/main/java/com/gogym/config/SecurityConfig.java

♻️ refactor: securityConfig HttpSecurity.csrf() 메서드 변경

---

src/main/java/com/gogym/config/WebConfig.java

♻️ refactor: Webconfig 테스트 주석 해제

---

src/main/java/com/gogym/member/controller/KakaoController.java
src/main/java/com/gogym/member/service/KakaoService.java

배포 후 카카오 로직 수정 -> uri 정적 값으로 변경 했습니다.

♻️ refactor: 배포 후 카카오 로직 수정 -> uri 정적 값으로 변경

---

src/main/java/com/gogym/member/service/KakaoService.java

♻️ refactor: 리다이랙션 uri 수정

---

src/main/java/com/gogym/member/controller/KakaoController.java
src/main/resources/application-prod.yml

♻️ refactor: 카카오 컨트롤러 DTO 반환으로 롤백

---

src/main/java/com/gogym/gympay/repository/impl/TransactionRepositoryImpl.java
src/main/java/com/gogym/post/dto/PostPageResponseDto.java

♻️refactor : 게시글 리스트 작성자 프로필 반환

---

src/main/java/com/gogym/post/repository/RecentViewRepository.java

#132 
- 게시글 조회시 알수없는 에러 발생
- 게시글 조회시 게시글이 뜨지 않거나, 최근 본 게시글에서 5개 이후로 저장이 안되는 이슈 발생하여 쿼리 파라미터를 수정하였습니다.

♻️refactor : 게시글 조회시 알수없는 에러 수정

---

src/main/java/com/gogym/member/service/ActivityService.java
src/test/java/com/gogym/member/service/ActivityServiceTest.java

♻️refactor : 최근본 게시글 잘못된 로직 수정

---

src/main/java/com/gogym/gympay/dto/PaymentResult.java
src/main/resources/application-prod.yml

🚑️ hotfix: 결제 단건 조회에서 알 수 없는 필드 무시하도록 수정

---

src/main/java/com/gogym/member/service/KakaoService.java

Refactor/kakao 서버 설정으로 변경

---

src/main/java/com/gogym/member/controller/AuthController.java
src/main/java/com/gogym/member/controller/KakaoController.java
src/main/java/com/gogym/member/dto/SignUpRequest.java

SignUpRequest에 iskako 추가하여 값을 변경할 수 있도록 변경했습니다.

♻️ refactor: isKakao 변경 안되는 것 리팩토링

---

src/main/java/com/gogym/gympay/controller/TransactionController.java
src/main/java/com/gogym/gympay/service/TransactionService.java

♻️ refactor: 거래날짜 등록 시 Message 전송 추가
